services:
  tom-auth:
    container_name: tom-auth09-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5010:80"
    volumes:
      - ./dataprotection-keys:/home/app/.aspnet/DataProtection-Keys

  